"use client";

import React, { createContext, useContext, useState, useCallback, useEffect } from "react";

type Lang = "en" | "ar";
type Dir = "ltr" | "rtl";

const translations = {
  en: {
    nav_home: "Home",
    nav_features: "Features",
    nav_how: "How It Works",
    nav_showcase: "Showcase",
    nav_contact: "Contact",
    hero_title: "Build Smarter. Ship Faster.",
    hero_subtitle: "JudyTech helps you design, build, and scale modern web applications with speed and precision.",
    hero_cta: "Get Started",
    hero_cta_primary: "Get Started",
    hero_cta_secondary: "View Demo",
    hero_badge: "Modern Web Development",
    hero_trust: "Trusted by developers and growing teams",
    hero_metric_1_value: "100",
    hero_metric_1_label: "Lighthouse",
    hero_metric_2_value: "<1s",
    hero_metric_2_label: "Load time",
    hero_metric_3_value: "A11Y",
    hero_metric_3_label: "WCAG AA",
    scroll_explore: "Scroll to explore",
    trust_title: "Used by developers and teams building modern products",
    proof_title: "Built with the modern web stack",
    proof_eyebrow: "Powered by",
    features_eyebrow: "Capabilities",
    process_eyebrow: "How it works",
    benefits_eyebrow: "Outcomes",
    cta_eyebrow: "Start today",
    stats_eyebrow: "By the numbers",
    stats_title: "Performance you can measure",
    stats_subtitle: "Built to load fast, feel responsive, and stay accessible.",
    stat_1_value: "100",
    stat_1_suffix: "",
    stat_1_label: "Lighthouse score",
    stat_2_value: "<1",
    stat_2_suffix: "s",
    stat_2_label: "Time to interactive",
    stat_3_value: "99",
    stat_3_suffix: "%",
    stat_3_label: "Accessibility (WCAG AA)",
    stat_4_value: "60",
    stat_4_suffix: "fps",
    stat_4_label: "Animation budget",
    testimonials_eyebrow: "Loved by builders",
    testimonials_title: "Teams ship faster with JudyTech",
    testimonials_subtitle: "Honest words from the people we've worked with.",
    testimonial_1_quote: "JudyTech rebuilt our marketing site in two weeks and conversion jumped 38%. The polish is genuinely best-in-class.",
    testimonial_1_name: "Sarah Lin",
    testimonial_1_role: "Head of Growth, Northwave",
    testimonial_2_quote: "Cleanest codebase we've inherited from an agency. Onboarding new engineers takes hours, not weeks.",
    testimonial_2_name: "Mateo Alvarez",
    testimonial_2_role: "Engineering Lead, Lumen Labs",
    testimonial_3_quote: "Sub-second loads, beautiful motion, and a team that actually cares about details. Highly recommended.",
    testimonial_3_name: "Aisha Rahman",
    testimonial_3_role: "Founder, Orbita",
    problem_title: "Building modern apps shouldn't be complicated",
    problem_subtitle: "Common roadblocks slow even the best teams down.",
    problem_1_title: "Slow development cycles",
    problem_1_desc: "Endless setup, configuration, and debugging eats away at delivery time.",
    problem_2_title: "Poor UI/UX consistency",
    problem_2_desc: "Designs drift across screens, frameworks, and team handoffs.",
    problem_3_title: "Hard-to-scale architectures",
    problem_3_desc: "Codebases that fight you the moment traffic or features grow.",
    solution_title: "A better way to build",
    solution_text: "JudyTech gives you the tools and structure to build fast, clean, and scalable products — without the complexity.",
    solution_chip_1: "Fast",
    solution_chip_2: "Clean",
    solution_chip_3: "Scalable",
    features_title: "Everything you need to ship",
    features_subtitle: "Clean foundations, modern patterns, and the polish your users expect.",
    feature_architecture_title: "Modern Architecture",
    feature_architecture_desc: "Clean, scalable structure ready for production from day one.",
    feature_performance_title: "High Performance",
    feature_performance_desc: "Optimized for speed and efficiency with sub-second loads.",
    feature_dx_title: "Developer Friendly",
    feature_dx_desc: "Built with best practices and clean code standards.",
    feature_deploy_title: "Ready for Deployment",
    feature_deploy_desc: "Seamless deployment with modern platforms like Vercel.",
    feature_responsive_title: "Responsive by Default",
    feature_responsive_desc: "Perfect experience across mobile, tablet, and desktop.",
    feature_customizable_title: "Customizable",
    feature_customizable_desc: "Flexible foundations that adapt to your product needs.",
    hiw_title: "How it works",
    hiw_subtitle: "From idea to launch in three focused steps.",
    hiw_step1_title: "Plan",
    hiw_step1_desc: "Define your product, audience, and structure before a single line of code.",
    hiw_step2_title: "Build",
    hiw_step2_desc: "Develop using modern tools, clean patterns, and a reusable design system.",
    hiw_step3_title: "Launch",
    hiw_step3_desc: "Deploy and scale with confidence on production-grade infrastructure.",
    showcase_title: "See what you can build",
    showcase_subtitle: "Clean UI. Fast performance. Scalable architecture.",
    benefits_title: "Why JudyTech",
    benefits_subtitle: "Real outcomes for teams that care about quality.",
    benefit_1_title: "Save development time",
    benefit_1_desc: "Skip the boilerplate and ship features instead.",
    benefit_2_title: "Improve product quality",
    benefit_2_desc: "Cleaner code, tighter UX, fewer regressions.",
    benefit_3_title: "Deliver better experiences",
    benefit_3_desc: "Interfaces that feel fast, polished, and intentional.",
    benefit_4_title: "Scale with confidence",
    benefit_4_desc: "Architectures that grow with your traffic and team.",
    cta_title: "Start building with JudyTech today",
    cta_subtitle: "Everything you need to create modern web experiences.",
    cta_button: "Get Started Now",
    contact_title: "Get In Touch",
    contact_subtitle: "We'd love to hear about your next big idea.",
    contact_form_first_name: "First name",
    contact_form_last_name: "Last name",
    contact_form_email: "Email",
    contact_form_phone: "Phone number",
    contact_form_subject: "Subject",
    contact_form_description: "Project details",
    contact_form_description_hint: "Tell us about your vision",
    contact_form_submit: "Send Message",
    contact_form_submitting: "Sending…",
    contact_form_success: "Thank you — we'll be in touch soon.",
    contact_form_error: "Something went wrong. Please try again.",
    contact_map_heading: "Our location",
    contact_address: "Jerusalem",
    contact_open_maps: "Open in Google Maps",
    footer_connect: "Connect",
    footer_quick_links: "Quick Links",
    footer_follow: "Follow us for the latest updates and insights.",
    footer_tagline: "Crafting premium digital experiences with cutting-edge technology.",
    footer_privacy: "Privacy",
    footer_terms: "Terms",
    footer_cookies: "Cookies",
    footer_rights: "All rights reserved.",
  },
  ar: {
    nav_home: "الرئيسية",
    nav_features: "المميزات",
    nav_how: "آلية العمل",
    nav_showcase: "المعرض",
    nav_contact: "تواصل معنا",
    hero_title: "ابنِ بذكاء. أطلق بسرعة.",
    hero_subtitle: "JudyTech تساعدك في تصميم وبناء وتوسيع تطبيقات الويب الحديثة بسرعة ودقة.",
    hero_cta: "ابدأ الآن",
    hero_cta_primary: "ابدأ الآن",
    hero_cta_secondary: "شاهد العرض",
    hero_badge: "تطوير ويب حديث",
    hero_trust: "موثوق من المطورين والفرق المتنامية",
    hero_metric_1_value: "100",
    hero_metric_1_label: "لايتهاوس",
    hero_metric_2_value: "<1ث",
    hero_metric_2_label: "وقت التحميل",
    hero_metric_3_value: "A11Y",
    hero_metric_3_label: "WCAG AA",
    scroll_explore: "اسحب للاستكشاف",
    trust_title: "يستخدمه مطورون وفرق يبنون منتجات حديثة",
    proof_title: "مبني بأحدث تقنيات الويب",
    proof_eyebrow: "مدعوم بـ",
    features_eyebrow: "الإمكانيات",
    process_eyebrow: "كيف يعمل",
    benefits_eyebrow: "النتائج",
    cta_eyebrow: "ابدأ اليوم",
    stats_eyebrow: "بالأرقام",
    stats_title: "أداء يمكن قياسه",
    stats_subtitle: "مبني ليكون سريع التحميل، متجاوب، وقابل للوصول.",
    stat_1_value: "100",
    stat_1_suffix: "",
    stat_1_label: "تقييم لايتهاوس",
    stat_2_value: "<1",
    stat_2_suffix: "ث",
    stat_2_label: "وقت التفاعل",
    stat_3_value: "99",
    stat_3_suffix: "%",
    stat_3_label: "إمكانية الوصول (WCAG AA)",
    stat_4_value: "60",
    stat_4_suffix: "إطار",
    stat_4_label: "ميزانية الحركة",
    testimonials_eyebrow: "محبوب من الصناع",
    testimonials_title: "فرق تطلق أسرع مع JudyTech",
    testimonials_subtitle: "كلمات صادقة من الأشخاص الذين عملنا معهم.",
    testimonial_1_quote: "أعادت JudyTech بناء موقعنا التسويقي خلال أسبوعين فقط وارتفعت معدلات التحويل بنسبة 38٪. مستوى الإتقان من الطراز الأول.",
    testimonial_1_name: "سارة لين",
    testimonial_1_role: "مديرة النمو، نورث ويف",
    testimonial_2_quote: "أنظف قاعدة كود ورثناها من وكالة. تأهيل المهندسين الجدد يأخذ ساعات، لا أسابيع.",
    testimonial_2_name: "ماتيو ألفاريز",
    testimonial_2_role: "قائد الهندسة، Lumen Labs",
    testimonial_3_quote: "تحميل بأقل من ثانية، حركة جميلة، وفريق يهتم فعلاً بالتفاصيل. أنصح بهم بشدة.",
    testimonial_3_name: "عائشة رحمن",
    testimonial_3_role: "مؤسسة، Orbita",
    problem_title: "بناء التطبيقات الحديثة لا يجب أن يكون معقداً",
    problem_subtitle: "عقبات شائعة تبطئ حتى أفضل الفرق.",
    problem_1_title: "دورات تطوير بطيئة",
    problem_1_desc: "الإعداد والتهيئة وتصحيح الأخطاء يستهلك وقت التسليم.",
    problem_2_title: "عدم اتساق واجهة المستخدم",
    problem_2_desc: "التصاميم تنحرف عبر الشاشات والأطر وتسليمات الفريق.",
    problem_3_title: "هياكل يصعب توسيعها",
    problem_3_desc: "قواعد كود تقاومك عند زيادة المستخدمين أو الميزات.",
    solution_title: "طريقة أفضل للبناء",
    solution_text: "JudyTech يمنحك الأدوات والبنية لبناء منتجات سريعة ونظيفة وقابلة للتوسع — بدون تعقيد.",
    solution_chip_1: "سريع",
    solution_chip_2: "نظيف",
    solution_chip_3: "قابل للتوسع",
    features_title: "كل ما تحتاجه للإطلاق",
    features_subtitle: "أسس نظيفة، أنماط حديثة، والصقل الذي يتوقعه مستخدموك.",
    feature_architecture_title: "هندسة حديثة",
    feature_architecture_desc: "بنية نظيفة وقابلة للتوسع جاهزة للإنتاج من اليوم الأول.",
    feature_performance_title: "أداء عالٍ",
    feature_performance_desc: "محسّن للسرعة والكفاءة بأوقات تحميل فائقة.",
    feature_dx_title: "صديق للمطور",
    feature_dx_desc: "مبني وفق أفضل الممارسات ومعايير الكود النظيف.",
    feature_deploy_title: "جاهز للنشر",
    feature_deploy_desc: "نشر سلس مع منصات حديثة مثل Vercel.",
    feature_responsive_title: "متجاوب افتراضياً",
    feature_responsive_desc: "تجربة مثالية عبر الجوال والتابلت والديسكتوب.",
    feature_customizable_title: "قابل للتخصيص",
    feature_customizable_desc: "أسس مرنة تتكيف مع احتياجات منتجك.",
    hiw_title: "كيف يعمل",
    hiw_subtitle: "من الفكرة إلى الإطلاق في ثلاث خطوات مركّزة.",
    hiw_step1_title: "خطط",
    hiw_step1_desc: "حدّد منتجك وجمهورك وهيكلك قبل أي سطر برمجي.",
    hiw_step2_title: "ابنِ",
    hiw_step2_desc: "طوّر باستخدام أدوات حديثة وأنماط نظيفة ونظام تصميم قابل لإعادة الاستخدام.",
    hiw_step3_title: "أطلق",
    hiw_step3_desc: "انشر ووسّع بثقة على بنية تحتية بمستوى الإنتاج.",
    showcase_title: "شاهد ما يمكنك بناؤه",
    showcase_subtitle: "واجهة نظيفة. أداء سريع. هندسة قابلة للتوسع.",
    benefits_title: "لماذا JudyTech",
    benefits_subtitle: "نتائج حقيقية للفرق التي تهتم بالجودة.",
    benefit_1_title: "وفّر وقت التطوير",
    benefit_1_desc: "تخطَّ القوالب الجاهزة وأطلق ميزات بدلاً من ذلك.",
    benefit_2_title: "حسّن جودة المنتج",
    benefit_2_desc: "كود أنظف، تجربة أدق، أخطاء أقل.",
    benefit_3_title: "قدّم تجارب أفضل",
    benefit_3_desc: "واجهات تبدو سريعة ومصقولة ومدروسة.",
    benefit_4_title: "وسّع بثقة",
    benefit_4_desc: "هندسات تنمو مع مرورك وفريقك.",
    cta_title: "ابدأ البناء مع JudyTech اليوم",
    cta_subtitle: "كل ما تحتاجه لإنشاء تجارب ويب حديثة.",
    cta_button: "ابدأ الآن",
    contact_title: "تواصل معنا",
    contact_subtitle: "نود أن نسمع عن فكرتك الرائعة التالية.",
    contact_form_first_name: "الاسم الأول",
    contact_form_last_name: "اسم العائلة",
    contact_form_email: "البريد الإلكتروني",
    contact_form_phone: "رقم الهاتف",
    contact_form_subject: "الموضوع",
    contact_form_description: "تفاصيل المشروع",
    contact_form_description_hint: "أخبرنا عن رؤيتك",
    contact_form_submit: "إرسال الرسالة",
    contact_form_submitting: "جاري الإرسال…",
    contact_form_success: "شكراً لك — سنتواصل معك قريباً.",
    contact_form_error: "حدث خطأ. حاول مرة أخرى.",
    contact_map_heading: "موقعنا",
    contact_address: "القدس",
    contact_open_maps: "فتح في خرائط جوجل",
    footer_connect: "تواصل",
    footer_quick_links: "روابط سريعة",
    footer_follow: "تابعنا للحصول على أحدث التحديثات والرؤى.",
    footer_tagline: "صياغة تجارب رقمية متميزة باستخدام أحدث التكنولوجيا.",
    footer_privacy: "الخصوصية",
    footer_terms: "الشروط",
    footer_cookies: "ملفات تعريف الارتباط",
    footer_rights: "جميع الحقوق محفوظة.",
  },
} as const;

type TranslationKey = keyof typeof translations.en;

interface LanguageContextType {
  lang: Lang;
  dir: Dir;
  toggleLang: () => void;
  t: (key: TranslationKey) => string;
}

const LanguageContext = createContext<LanguageContextType | null>(null);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLang] = useState<Lang>("en");
  const dir: Dir = lang === "ar" ? "rtl" : "ltr";

  const toggleLang = useCallback(() => {
    setLang((prev) => (prev === "en" ? "ar" : "en"));
  }, []);

  const t = useCallback(
    (key: TranslationKey): string => {
      return translations[lang][key];
    },
    [lang]
  );

  useEffect(() => {
    document.documentElement.setAttribute("dir", dir);
    document.documentElement.setAttribute("lang", lang);
  }, [dir, lang]);

  return (
    <LanguageContext.Provider value={{ lang, dir, toggleLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) throw new Error("useLanguage must be used within LanguageProvider");
  return context;
}
